"""
C Code Generator for iq_ff Neural Network
==========================================
Generates a minimal, self-contained C header that runs the trained
4→N→1 tanh MLP with zero framework overhead.

Key optimisations applied at generation time:
  1. Normalisation fused into layer-1 weights & biases
       W1_fused[:, j] = W1[:, j] / scaler_std[j]
       b1_fused       = b1 - W1 @ (scaler_mean / scaler_std)
  2. De-normalisation fused into output layer
       W2_fused = W2 * y_std
       b2_fused = b2 * y_std + y_mean
  3. All weights emitted as float32 literals — single assignment, no loop.
  4. Optional fast tanh approximation (Padé rational, max error < 5e-4).

Result for 4→4→1 on Cortex-M4 @ 170 MHz (with -O2):
  ≈ 4 tanhf() calls  + ~25 VMLA  ≈  3–5 µs
  With fast_tanh:                 ≈  1–2 µs

Usage:
  python3 codegen_c.py
  → model/iq_ff_nn.h   (drop into STM32 project, #include it)
"""

import json
import os
import math

import numpy as np

MODEL_DIR    = "model"
META_FILE    = os.path.join(MODEL_DIR, "iq_ff_meta.json")
WEIGHTS_FILE = os.path.join(MODEL_DIR, "iq_ff_weights.json")
OUT_H        = os.path.join(MODEL_DIR, "iq_ff_nn.h")

FAST_TANH    = True   # True → Padé approximation; False → libm tanhf()
FUNC_NAME    = "iq_ff_predict"

# ── Load meta & weights ────────────────────────────────────────────────────────
with open(META_FILE) as f:
    meta = json.load(f)
with open(WEIGHTS_FILE) as f:
    raw_w = json.load(f)

hidden      = meta["hidden_layers"]
input_cols  = meta["input_cols"]
n_in        = len(input_cols)
scaler_type = meta.get("scaler_X_type", "StandardScaler")

if scaler_type == "RobustScaler":
    X_center = np.array(meta["scaler_X_center"], dtype=np.float64)
    X_scale  = np.array(meta["scaler_X_scale"],  dtype=np.float64)
else:
    X_center = np.array(meta["scaler_X_mean"], dtype=np.float64)
    X_scale  = np.array(meta["scaler_X_std"],  dtype=np.float64)

y_mean = float(meta["scaler_y_mean"][0])
y_std  = float(meta["scaler_y_std"][0])

# Build layer list: [(W, b), ...]
# PyTorch sequential: even indices = Linear
layers = []
pt_idx = 0
prev = n_in
layer_sizes = hidden + [1]
for h in layer_sizes:
    W = np.array(raw_w[f"net.{pt_idx}.weight"], dtype=np.float64)  # (h, prev)
    b = np.array(raw_w[f"net.{pt_idx}.bias"],   dtype=np.float64)  # (h,)
    layers.append((W, b))
    pt_idx += 2
    prev = h

# ── Fuse normalisation into layer 0 ───────────────────────────────────────────
# forward: h = tanh(W0 @ ((x - center) / scale) + b0)
#            = tanh((W0 / scale) @ x  +  (b0 - W0 @ (center/scale)))
W0, b0 = layers[0]
W0_f   = W0 / X_scale[np.newaxis, :]        # broadcast: divide each column j by scale[j]
b0_f   = b0 - W0 @ (X_center / X_scale)
layers[0] = (W0_f, b0_f)

# ── Fuse de-normalisation into last layer ──────────────────────────────────────
# last layer is linear: y_raw = WN @ h + bN
# output = y_raw * y_std + y_mean
WN, bN = layers[-1]
WN_f   = WN * y_std
bN_f   = bN * y_std + y_mean
layers[-1] = (WN_f, bN_f)

# ── Helpers ────────────────────────────────────────────────────────────────────
def f32(v):
    """Format a Python float as a C float32 literal."""
    return f"{float(v):.9g}f"


def emit_dot(result_var, W_row, input_vars, bias):
    """
    Emit: float <result_var> = w0*x0 + w1*x1 + ... + bias;
    Fully unrolled — no loops, no arrays.
    """
    terms = [f"{f32(W_row[j])}*{input_vars[j]}" for j in range(len(W_row))]
    # Split to keep lines readable (≤3 terms per line)
    rhs = " + ".join(terms) + f" + {f32(bias)}"
    return f"    float {result_var} = {rhs};\n"


# ── Generate C ────────────────────────────────────────────────────────────────
lines = []

# Determine if model was trained in residual mode
residual_mode = meta.get("residual_mode", False)
residual_comment = (
    "/* OUTPUT: residual current delta_iq = iq - iq_I_term (A)         */\n"
    "/* MCU usage:  float iq_ff = iq_ff_predict(...) + iq_I_term;       */\n"
    if residual_mode else
    "/* OUTPUT: feedforward current iq_ff (A)                           */\n"
)

# Header guard
guard = "IQ_FF_NN_H"
lines += [
    f"/* Auto-generated by codegen_c.py — do not edit manually */\n",
    f"/* Network: {n_in} → {' → '.join(str(h) for h in hidden)} → 1  (tanh hidden, linear output) */\n",
    f"/* Normalisation fused into weights — no pre/post-processing needed */\n",
    residual_comment,
    f"\n",
    f"#ifndef {guard}\n",
    f"#define {guard}\n",
    f"\n",
]

if FAST_TANH:
    lines += [
        "/* Fast tanh: Padé [5/4] rational approximation, |error| < 5e-4 for all x */\n",
        "/* Clamps to ±1 for |x| > 4.97 (where tanh is already ≥ 0.9999). */\n",
        "__attribute__((always_inline)) static inline float nn_tanh(float x)\n",
        "{\n",
        "    if (x >  4.97f) return  1.0f;\n",
        "    if (x < -4.97f) return -1.0f;\n",
        "    float x2 = x * x;\n",
        "    return x * (135135.0f + x2 * (17325.0f + x2 * (378.0f + x2)))\n",
        "             / (135135.0f + x2 * (62370.0f + x2 * (3150.0f + x2 * 28.0f)));\n",
        "}\n",
        "\n",
    ]
    tanh_call = "nn_tanh"
    includes  = ""
else:
    lines += [
        "#include <math.h>\n",
        "\n",
    ]
    tanh_call = "tanhf"
    includes  = "#include <math.h>\n"

# Function signature
arg_list = ", ".join(f"float {c}" for c in input_cols)
lines += [
    f"__attribute__((optimize(\"O2\")))\n",
    f"static inline float {FUNC_NAME}({arg_list})\n",
    "{\n",
]

# Layer 0: fused normalisation + linear + tanh
W0f, b0f = layers[0]
input_vars = list(input_cols)   # raw inputs (normalisation already fused in)
hidden_vars = []
for i in range(W0f.shape[0]):
    pre_var  = f"z0_{i}"
    act_var  = f"h0_{i}"
    lines.append(emit_dot(pre_var, W0f[i], input_vars, b0f[i]))
    lines.append(f"    float {act_var} = {tanh_call}({pre_var});\n")
    hidden_vars.append(act_var)

# Middle hidden layers (if any)
for layer_idx in range(1, len(layers) - 1):
    Wl, bl = layers[layer_idx]
    next_vars = []
    for i in range(Wl.shape[0]):
        pre_var = f"z{layer_idx}_{i}"
        act_var = f"h{layer_idx}_{i}"
        lines.append(emit_dot(pre_var, Wl[i], hidden_vars, bl[i]))
        lines.append(f"    float {act_var} = {tanh_call}({pre_var});\n")
        next_vars.append(act_var)
    hidden_vars = next_vars

# Output layer: fused de-normalisation (linear, no activation)
WN_f, bN_f = layers[-1]
lines.append(emit_dot("y", WN_f[0], hidden_vars, bN_f[0]))
lines += [
    "    return y;\n",
    "}\n",
    "\n",
    f"#endif /* {guard} */\n",
]

# ── Write file ─────────────────────────────────────────────────────────────────
os.makedirs(MODEL_DIR, exist_ok=True)
with open(OUT_H, "w") as f:
    f.writelines(lines)

print(f"Generated: {OUT_H}")
print()

# ── Numerical verification ─────────────────────────────────────────────────────
# Re-run forward pass in Python with fused weights and compare to original
def py_tanh(x):
    return math.tanh(x)

def fused_forward(x_raw):
    h = x_raw.copy()
    for i, (W, b) in enumerate(layers):
        pre = W @ h + b
        if i < len(layers) - 1:
            h = np.tanh(pre)
        else:
            h = pre
    return float(h[0])

# Original (unfused) inference for comparison
with open(WEIGHTS_FILE) as f:
    raw_w2 = json.load(f)

def orig_forward(x_raw):
    # normalise
    h = (x_raw - X_center) / X_scale
    pt2 = 0
    for i, sz in enumerate(hidden + [1]):
        W = np.array(raw_w2[f"net.{pt2}.weight"])
        b = np.array(raw_w2[f"net.{pt2}.bias"])
        pre = W @ h + b
        h = np.tanh(pre) if i < len(hidden) else pre
        pt2 += 2
    return float(h[0]) * y_std + y_mean

rng = np.random.default_rng(0)
test_pts = rng.standard_normal((100, n_in)) * X_scale + X_center
errs = []
for pt in test_pts:
    errs.append(abs(fused_forward(pt) - orig_forward(pt)))

max_err = max(errs)
print(f"Fused vs original max error: {max_err:.2e} A  {'✓ OK' if max_err < 1e-4 else '✗ WARNING'}")
print()

# ── Print cycle estimate ───────────────────────────────────────────────────────
n_tanh = sum(h for h in hidden)   # one tanh per hidden neuron
n_macs = n_in * hidden[0]
for i in range(len(hidden) - 1):
    n_macs += hidden[i] * hidden[i+1]
n_macs += hidden[-1] * 1

print("── Cycle estimate on Cortex-M4 @ 170 MHz ──")
print(f"  MACs (FP32 VMLA, ~3 cycles each) : {n_macs} × 3 = {n_macs*3} cycles")
if FAST_TANH:
    print(f"  nn_tanh (~15 cycles each)         : {n_tanh} × 15 = {n_tanh*15} cycles")
    total = n_macs * 3 + n_tanh * 15
else:
    print(f"  tanhf  (~80 cycles each)          : {n_tanh} × 80 = {n_tanh*80} cycles")
    total = n_macs * 3 + n_tanh * 80
print(f"  Estimated total                   : ~{total} cycles  ≈  {total/170:.1f} µs")
print()
print("Drop model/iq_ff_nn.h into your STM32 project and call:")
print(f"  float iq_ff = {FUNC_NAME}(omega_m, omega_m_ref, dwr_dt, imr);")
